name: Run Cypress Tests

on: [push, pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Cypress tests in Docker
      run: npm run cypress:docker:run
